version: '3.7'

volumes:
  datafiles:
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=hasan12@
      - MYSQL_DATABASE=auth
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d

      - datafiles:/etc/mysql/conf.d
    

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=hasan12@
      - MYSQL_DATABASE=auth
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql #it means it depends on above service