variables:
  DOCKER_REGISTRY: public.ecr.aws/b9e6a7a5/
  APP_NAME: dockerimage
  DOCKER_HOST: tcp://docker:2375
  AWS_REGION: us-east-1

jobs:

  push:
    branches:
      - main
  publish:
    image: 
      name: amazon/aws-cli
      entrypoint: [""] #deciding entry point for script
    services:
      - docker:dind
    before_script:
      - amazon-linux-extras install docker
      - aws --version
      - docker --version
    script:
      - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
      - aws ecr get-login-password --region $AWS_REGION| docker login --username  AWS --password-stdin $DOCKER_REGISTRY
      - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID